kind: DevWorkspaceTemplate
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: my-plugin-test
spec:
  components:
    - name: my-plugin
      container:
        image: "quay.io/wto/web-terminal-tooling"
        args: ["tail", "-f", "/dev/null"]
